In [4]:
import numpy as np
import pandas as pandas
import folium

In [5]:
import warnings 

warnings.filterwarnings(action='ignore')

In [8]:
# folium으로 지도 찍어보기
m = folium.Map(
    location = [33.364969, 126.529117] #여기에 좌표 넣기
)

m

In [10]:
# 지도 저장

m.save('index.html')

In [26]:
# 지도에 마커 찍어보기

m = folium.Map(
    location = [33.364969, 126.529117],
    tiles = 'OpenStreetMap',
    zoom_start = 11
)

tooltip = 'Click!!'  #마우스를 오버했을 때 나오는 문구

folium.Marker(
    [33.364969, 126.529117],
    popup = "<strong>hello world</strong>",
    tooltip = tooltip
).add_to(m)


m

In [29]:
# 지도에 마커 찍어보기

m = folium.Map(
    location = [33.364969, 126.529117],
    # tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = 'Click!!'  #마우스를 오버했을 때 나오는 문구

#한라산
folium.Marker(
    [33.364969, 126.529117],
    popup = "<strong>한라산</strong>",
    tooltip = tooltip
).add_to(m)

#제주국제공항
folium.Marker(
    [33.507340, 126.493437],
    popup = "<strong>제주국제공항</strong>",
    tooltip = tooltip
).add_to(m)

#바울랩
folium.Marker(
    [33.508515, 126.541033],
    popup = "<strong>바울랩</strong>",
    tooltip = tooltip
).add_to(m)

m

In [38]:
# 지도에 마커 찍어보기

m = folium.Map(
    location = [33.364969, 126.529117],
    # tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = 'Click!!'  #마우스를 오버했을 때 나오는 문구

#한라산
folium.Marker(
    [33.364969, 126.529117],
    popup = "<strong>한라산</strong>",
    icon = folium.Icon(color='#ffffff', icon='info-sign'),
    tooltip = tooltip
).add_to(m)

#제주국제공항
folium.Marker(
    [33.507340, 126.493437],
    popup = "<strong>제주국제공항</strong>",
    icon = folium.Icon(color='green', icon='bookmark'),
    tooltip = tooltip
).add_to(m)

#바울랩
folium.Marker(
    [33.508515, 126.541033],
    popup = "<strong>바울랩</strong>",
    icon = folium.Icon(color='blue', icon='magnifying-glass', prefix='fa'),
    tooltip = tooltip
).add_to(m)

m

In [39]:
import numpy as np
import pandas as pd
import folium

In [41]:
oreum = pd.read_csv("oreum.csv", encoding='cp949')
oreum

,읍면동,오름명,소재지,위도,경도,주차장,화장실,표고(m),데이터기준일자
0,대정읍,송악산(절울이),제주특별자치도 서귀포시 대정읍 상모리 산 2,33.199409,126.290780,Y,Y,104.0,2024-05-02
1,대정읍,섯알오름,제주특별자치도 서귀포시 대정읍 상모리 1618,33.204254,126.281676,Y,Y,40.7,2024-05-02
2,대정읍,가시오름,제주특별자치도 서귀포시 대정읍 동일리 1209,33.253363,126.249055,Y,N,106.5,2024-05-02
3,대정읍,녹남봉,제주특별자치도 서귀포시 대정읍 신도리 1304,33.279815,126.195483,N,N,100.4,2024-05-02
4,남원읍,물영아리,제주특별자치도 서귀포시 남원읍 수망리 산 189,33.370809,126.693520,Y,N,508.0,2024-05-02
...,...,...,...,...,...,...,...,...,...
63,서홍동,시오름,제주특별자치도 서귀포시 서홍동 산 1,33.361667,126.529167,N,N,757.8,2024-05-02
64,대륜동,고근산,제주특별자치도 서귀포시 서호동 1286-1,33.266364,126.512309,N,N,396.2,2024-05-02
65,중문동,거린사슴,제주특별자치도 서귀포시 대포동 산 2-1,33.307313,126.454127,Y,Y,742.9,2024-05-02
66,중문동,베릿내오름,제주특별자치도 서귀포시 중문동 3712,33.251430,126.434824,Y,Y,101.2,2024-05-02
67,중문동,법정악,제주특별자치도 서귀포시 하원동 산 1,33.258346,126.452100,Y,Y,760.1,2024-05-02

In [43]:
oreum.isnull()
oreum.isnull().sum()

읍면동        0
오름명        0
소재지        0
위도         0
경도         0
주차장        0
화장실        0
표고(m)      0
데이터기준일자    0
dtype: int64

In [44]:
oreum[['화장실']].value_counts()

화장실
N      49
Y      19
Name: count, dtype: int64

In [45]:
oreum[['주차장']].value_counts()

주차장
N      44
Y      24
Name: count, dtype: int64

In [46]:
oreum.iloc[0]

읍면동                             대정읍
오름명                        송악산(절울이)
소재지        제주특별자치도 서귀포시 대정읍 상모리 산 2
위도                        33.199409
경도                        126.29078
주차장                               Y
화장실                               Y
표고(m)                         104.0
데이터기준일자                  2024-05-02
Name: 0, dtype: object

In [47]:
oreum.iloc[0]['위도']

np.float64(33.1994088)

In [48]:
oreum.iloc[0]['경도']

np.float64(126.2907797)

In [49]:
oreum.shape

(68, 9)

In [50]:
len(oreum)

68

In [51]:
for i in range(oreum.shape[0]):
    o_name = oreum.iloc[i]['오름명']
    lat = oreum.iloc[i]['위도']
    long = oreum.iloc[i]['경도']
    print(o_name, lat, long)

송악산(절울이) 33.1994088 126.2907797
섯알오름 33.2042537 126.281676
가시오름  33.2533626 126.2490546
녹남봉 33.2798153 126.1954827
물영아리 33.3708091 126.6935196
머체오름 33.342895 126.6494133
이승이 33.342895 126.6494133
사려니오름 33.342895 126.6494133
민오름 33.3508829 126.6980129
운지오름 33.320538 126.7451549
자배봉 33.342895 126.6494133
생길이 33.342895 126.6494133
큰걸세 33.3616666 126.5291666
족은걸세 33.3616666 126.5291666
수악 33.3616666 126.5291666
한남리머체왓숲길 33.3305697 126.6740675
일출봉 33.4584473 126.9425348
멀미오름 33.4786495 126.8840616
멀미알오름 33.4786495 126.8840616
식산봉(바우오름) 33.4656758 126.9196473
큰물메(대왕수봉) 33.4398545 126.8991383
궁대악 33.4349078 126.8170896
뒤꾸부니 33.4310244 126.8273298
모구리오름 33.4080291 126.8271111
유건에오름 33.4135945 126.8467892
통오름 33.3944955 126.8567401
독자봉 33.3877114 126.8541774
남산봉 33.3860915 126.8081632
낭끼오름 33.4355716 126.842924
모구리알오름 33.4080291 126.8271111
대왕산 33.456482 126.8727771
군산 33.2551426 126.3683605
단산(바굼지오름) 33.2469709 126.3206311
월라봉(다래오름) 33.2442794 126.3499008
대병악(여진머리) 33.3066236 126.3704559
북오름 33.3056468 126.3313681
남송악(남소로기) 33.3050158 126.3046682
광해악(넙게오름) 33.2871076 126.3162332
논오름 33.2666345 126.3408035
금산 33.2360818 126.2870485
용머리 33.2340447 126.3141969
왕이메 33.340233 126.374785
따라비오름 33.3708091 126.6935196
대록산(큰사슴이) 33.3708091 126.6935196
달산봉 33.3485734 126.8327895
제석오름 33.3470334 126.836251
매봉 33.3225332 126.8228665
영주산 33.4048901 126.7976481
좌보미 33.4377473 126.7917034
백약이오름 33.4377473 126.7917034
갑선이 33.3708091 126.6935196
가세오름 33.3314602 126.7815087
토산봉 33.3223939 126.7735897
붉은오름 33.3708091 126.6935196
개오름 33.3863435 126.7997102
갑마장길 33.3708091 126.6935196
제지오름(절오름) 33.240809 126.6101421
월라산(도라미) 33.2705143 126.6046518
칡오름 33.3616666 126.5291666
영천오름 33.3616666 126.5291666
미악산(솔오름) 33.3017594 126.5573394
삼매봉 33.2539385 126.5595922
하논-보로미 33.2537823 126.5422628
시오름 33.3616666 126.5291666
고근산 33.2663637 126.5123088
거린사슴 33.3073127 126.4541266
베릿내오름 33.2514303 126.4348243
법정악 33.2583461 126.4521002

In [ ]:
# 기본지도
m = folium.Map(
    location = [33.364969, 126.529117],
    tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = "Click!!"

# 오름 정보 추가
for i in range(oreum.shape[0]):
    o_name = oreum.iloc[i]['오름명']
    lat = oreum.iloc[i]['위도']
    long = oreum.iloc[i]['경도']

    folium.Marker(
        [lat, long],
        popup = f"<strong>{o_name}</strong>",
        tooltip = tooltip
    ).add_to(m)

m

In [57]:
# 오름 상세정보 추가하기

# 기본지도
m = folium.Map(
    location = [33.364969, 126.529117],
    tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = "Click!!"

# 오름 정보 추가
for i in range(oreum.shape[0]):
    folium.Marker(
        [oreum.iloc[i]['위도'], oreum.iloc[i]['경도']],
        popup = f"<strong>{oreum.iloc[i]['오름명']}</strong>",
        tooltip = tooltip
    ).add_to(m)

m

In [58]:
# 오름 상세정보 추가하기

# 기본지도
m = folium.Map(
    location = [33.364969, 126.529117],
    tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = "Click!!"

# 오름 정보 추가
for i in range(oreum.shape[0]):
    folium.Marker(
        [oreum.iloc[i]['위도'], oreum.iloc[i]['경도']],
        popup = f"<div style='width:100px'><strong>{oreum.iloc[i]['오름명']}</strong><br>\
            주차장: {oreum.iloc[i]['주차장']}<br>\
            화장실: {oreum.iloc[i]['화장실']}<br>\
            </div>",
        tooltip = tooltip
    ).add_to(m)

m

In [63]:
#이미지column추가
oreum['이미지'] = oreum['오름명']+'.jpg'
oreum

,읍면동,오름명,소재지,위도,경도,주차장,화장실,표고(m),데이터기준일자,이미지
0,대정읍,송악산(절울이),제주특별자치도 서귀포시 대정읍 상모리 산 2,33.199409,126.290780,Y,Y,104.0,2024-05-02,송악산(절울이).jpg
1,대정읍,섯알오름,제주특별자치도 서귀포시 대정읍 상모리 1618,33.204254,126.281676,Y,Y,40.7,2024-05-02,섯알오름.jpg
2,대정읍,가시오름,제주특별자치도 서귀포시 대정읍 동일리 1209,33.253363,126.249055,Y,N,106.5,2024-05-02,가시오름 .jpg
3,대정읍,녹남봉,제주특별자치도 서귀포시 대정읍 신도리 1304,33.279815,126.195483,N,N,100.4,2024-05-02,녹남봉.jpg
4,남원읍,물영아리,제주특별자치도 서귀포시 남원읍 수망리 산 189,33.370809,126.693520,Y,N,508.0,2024-05-02,물영아리.jpg
...,...,...,...,...,...,...,...,...,...,...
63,서홍동,시오름,제주특별자치도 서귀포시 서홍동 산 1,33.361667,126.529167,N,N,757.8,2024-05-02,시오름.jpg
64,대륜동,고근산,제주특별자치도 서귀포시 서호동 1286-1,33.266364,126.512309,N,N,396.2,2024-05-02,고근산.jpg
65,중문동,거린사슴,제주특별자치도 서귀포시 대포동 산 2-1,33.307313,126.454127,Y,Y,742.9,2024-05-02,거린사슴.jpg
66,중문동,베릿내오름,제주특별자치도 서귀포시 중문동 3712,33.251430,126.434824,Y,Y,101.2,2024-05-02,베릿내오름.jpg
67,중문동,법정악,제주특별자치도 서귀포시 하원동 산 1,33.258346,126.452100,Y,Y,760.1,2024-05-02,법정악.jpg

In [67]:
# 오름 상세정보 추가하기

# 기본지도
m = folium.Map(
    location = [33.364969, 126.529117],
    tiles = 'OpenStreetMap',
    zoom_start = 10
)

tooltip = "Click!!"

# 오름 정보 추가
for i in range(oreum.shape[0]):
    folium.Marker(
        [oreum.iloc[i]['위도'], oreum.iloc[i]['경도']],
        popup = f"<div style='width:100px'><strong>{oreum.iloc[i]['오름명']}</strong><br>\
            주차장: {oreum.iloc[i]['주차장']}<br>\
            화장실: {oreum.iloc[i]['화장실']}<br>\
            <img width='80px' src='a.jpg'><br>\
            <a href='https://www.visitjeju.net/en/search?q=%EC%98%A4%EB%A6%84#'>상세페이지 이동</a></div>",
        tooltip = tooltip
    ).add_to(m)

m.save('index.html')